version: "3"

services:
  base-slim:
    image: chartjs-node-canvas-base-slim
    build:
      context: .
      dockerfile: docker/slim/base.Dockerfile
    container_name: chartjs-node-canvas-base-slim
  build-slim:
    image: chartjs-node-canvas-build-slim
    depends_on: 
      - base-slim
    build:
      context: .
      dockerfile: docker/slim/build.Dockerfile
    container_name: chartjs-node-canvas-build-slim
  test-slim:
    image: chartjs-node-canvas-build-slim
    container_name: chartjs-node-canvas-test-slim
    volumes:
      - ./testData:/usr/server/testData
    depends_on: 
      - build-slim
    environment:
      - NODE_ENV=test
      - FONTCONFIG_PATH=/etc/fonts
    command: npm run test
  production-slim:
    image: chartjs-node-canvas-slim
    depends_on: 
      - test-slim
    build:
      context: .
      dockerfile: docker/slim/production.Dockerfile
    container_name: chartjs-node-canvas-slim
    environment:
      - NODE_ENV=production

  base-ubuntu:
    image: chartjs-node-canvas-base-ubuntu
    build:
      context: .
      dockerfile: docker/ubuntu/base.Dockerfile
    container_name: chartjs-node-canvas-base-ubuntu
  build-ubuntu:
    image: chartjs-node-canvas-build-ubuntu
    depends_on: 
      - base-ubuntu
    build:
      context: .
      dockerfile: docker/ubuntu/build.Dockerfile
    container_name: chartjs-node-canvas-build-ubuntu
  test-ubuntu:
    image: chartjs-node-canvas-build-ubuntu
    container_name: chartjs-node-canvas-test-ubuntu
    volumes:
      - ./testData:/usr/server/testData
    depends_on: 
      - build-ubuntu
    environment:
      - NODE_ENV=test
      - FONTCONFIG_PATH=/etc/fonts
    command: npm run test